In [1]:
import numpy as np

In [4]:
array1 = np.array([1, 2, 3])
print('array1 type:', type(array1))
print('array1 shape:', array1.shape)
print('array1 dimension:', array1.ndim)
print('array1 data type:', array1.dtype)

array1 type: <class 'numpy.ndarray'>
array1 shape: (3,)
array1 dimension: 1
array1 data type: int64


In [5]:
array1_float = array1.astype('float64')
print(array1_float, array1_float.dtype)

[1. 2. 3.] float64


In [6]:
sequence_array = np.arange(0, 10, 1)
print(sequence_array)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
zero_array = np.zeros((3, 2), 'int32')
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [9]:
one_array = np.ones((2, 3))
print(one_array)

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(2, 5)
print(array2)

array3 = array2.reshape(-1, 2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [13]:
print(array1[2])
print(array2[0, 2])

2
2


In [14]:
print(array1[2:4])
print(array1[2:])
print(array1[:4])
print(array1[:])

[2 3]
[2 3 4 5 6 7 8 9]
[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [15]:
print(array2[1:, 2:4])

[[7 8]]


In [20]:
print(array2)
print(array2[[0, 1], 2])
print(array2[[0, 1], 0:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]
[2 7]
[[0 1]
 [5 6]]


In [21]:
print(array1[array1>5])

[6 7 8 9]


In [22]:
org_array = np.array([3, 1, 9, 5])
print(org_array)
sort_array1 = np.sort(org_array)
print(sort_array1)
print(org_array)
sort_array2 = org_array.sort()
print(sort_array2)
print(org_array)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [24]:
array2d = np.array([[8, 12], [7, 1]])
print(np.sort(array2d, axis=0))
print(np.argsort(array2d, axis=0))
print(np.sort(array2d, axis=1))
print(np.argsort(array2d, axis=1))

[[ 7  1]
 [ 8 12]]
[[1 1]
 [0 0]]
[[ 8 12]
 [ 1  7]]
[[0 1]
 [1 0]]


In [25]:
org_array = np.array([3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(sort_indices)

[1 0 3 2]


In [26]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[7, 8], [9, 10], [11, 12]])
print(np.dot(A, B))

[[ 58  64]
 [139 154]]


In [27]:
A = np.array([[1, 2], [3, 4]])
transpose_mat = np.transpose(A)
print(transpose_mat)

[[1 3]
 [2 4]]
