In [1]:
import numpy as np

dense = np.array([[3, 0, 1], [0, 2, 0]])

In [3]:
from scipy import sparse

data = np.array([3, 1, 2])

row_pos = np.array([0, 0, 1])
col_pos = np.array([0, 2, 1])

sparse_coo = sparse.coo_matrix((data, (row_pos, col_pos)))

sparse_coo.toarray()

array([[3, 0, 1],
       [0, 2, 0]])

In [4]:
dense2 = np.array(
    [
        [0, 0, 1, 0, 0, 5],
        [1, 4, 0, 3, 2, 5],
        [0, 6, 0, 3, 0, 0],
        [2, 0, 0, 0, 0, 0],
        [0, 0, 0, 7, 0, 8],
        [1, 0, 0, 0, 0, 0],
    ]
)

data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

sparse_coo = sparse.coo_matrix((data2, (row_pos, col_pos)))

row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])

sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print(sparse_coo.toarray())
print(sparse_csr.toarray())

[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [5]:
dense3 = np.array(
    [
        [0, 0, 1, 0, 0, 5],
        [1, 4, 0, 3, 2, 5],
        [0, 6, 0, 3, 0, 0],
        [2, 0, 0, 0, 0, 0],
        [0, 0, 0, 7, 0, 8],
        [1, 0, 0, 0, 0, 0],
    ]
)

coo = sparse.coo_matrix(dense3)
csr = sparse.csr_matrix(dense3)

In [10]:
coo.getcol(0).toarray()

array([[0],
       [1],
       [0],
       [2],
       [0],
       [1]])